issue_5 - property_type Lookup Table
your-rents/your-rents-api pull request #13
Opened 2024-11-30 02:45 UTC by egch

2024-12-02 13:51 UTC, benfante commented
I fixed the build process. Now it creates and populates both schemas (global and tenant).

Please implement the reference to the property_type as a  numberic foreign key.

2024-12-03 16:45 UTC, benfante requested changes
Please resolve the PropertyType in the Property.

2024-12-03 16:45 UTC, benfante commented on src/main/java/com/yourrents/api/property/Property.java
> +public record Property(UUID uuid, String name, UUID typeUuid, String description,
As Property-PropertyType it is a many-to-one relationship I would like to resolve it eagerly.

So it should be:

```java
public record Property(UUID uuid, String name, PropertyType type, String description,
  // etc.
```

Of course you'll need to adapt the other classes for using it.

2024-12-03 18:36 UTC, egch commented
Implemented changes as required. @benfante please review

2024-12-03 20:30 UTC, merged